INSERT INTO gondolas (titulo, secciones, tipo_titulo, tipo_secciones) VALUES
('Frutas y Verduras', 'Hortalizas', 'ALIMENTOS', 'CENTRALES'),
('Carnes y Embutidos', 'Cortes Frescos', 'ALIMENTOS', 'PARED'),
('Panadería', 'Repostería', 'ALIMENTOS', 'CABECERA'),
('Lácteos', 'Quesos y Yogures', 'ALIMENTOS', 'ESPECIALIZADA'),
('Bebidas', 'Jugos y Refrescos', 'ALIMENTOS', 'CENTRALES'),
('Condimentos', 'Especias y Salsas', 'ALIMENTOS', 'PARED'),
('Snacks', 'Chips y Dulces', 'ALIMENTOS', 'CABECERA'),
('Electrodomésticos', 'Cocción', 'ELECTRONICA', 'CENTRALES'),
('Muebles y Decoración', 'Accesorios', 'ALIMENTOS', 'PARED'),
('Juguetes', 'Infantiles', 'JUGUETES', 'ESPECIALIZADA'),
('Productos de Limpieza', 'Hogar', 'LIMPIEZA', 'CENTRALES'),
('Cosméticos y Cuidado Personal', 'Belleza', 'PERFUMERIA', 'PARED'),
('Artículos de Oficina', 'Papelería', 'ALIMENTOS', 'CABECERA'),
('Ropa y Calzado', 'Moda', 'ALIMENTOS', 'ESPECIALIZADA'),
('Tecnología', 'Accesorios Electrónicos', 'ELECTRONICA', 'CENTRALES'),
('Casa y Jardín', 'Decoración', 'ALIMENTOS', 'PARED'),
('Libros y Revistas', 'Lectura', 'ALIMENTOS', 'CABECERA'),
('Preparación de Comida', 'Utensilios', 'ALIMENTOS', 'ESPECIALIZADA'),
('Bienestar y Salud', 'Suplementos', 'ALIMENTOS', 'CENTRALES'),
('Bolsos y Accesorios', 'Moda', 'ALIMENTOS', 'PARED'),
('Cuidado de Mascotas', 'Alimentos y Accesorios', 'ALIMENTOS', 'CABECERA'),
('Gastronomía Internacional', 'Productos del Mundo', 'ALIMENTOS', 'ESPECIALIZADA'),
('Artículo de Fiesta', 'Decoraciones', 'ALIMENTOS', 'CENTRALES'),
('Revistas de Estilo de Vida', 'Entretenimiento', 'ALIMENTOS', 'PARED'),
('Productos Orgánicos', 'Sustentabilidad', 'ALIMENTOS', 'CABECERA'),
('Alimentos Congelados', 'Comidas Preparadas', 'ALIMENTOS', 'ESPECIALIZADA'),
('Comida Rápida', 'Snacks y Salsas', 'ALIMENTOS', 'CENTRALES'),
('Aceites y Vinagres', 'Especias', 'ALIMENTOS', 'PARED'),
('Menaje de Cocina', 'Utensilios', 'ALIMENTOS', 'CABECERA'),
('Decoración del Hogar', 'Accesorios', 'ALIMENTOS', 'ESPECIALIZADA'),
('Artículos de Seguridad', 'Seguridad del Hogar', 'ALIMENTOS', 'CENTRALES'),
('Bebidas Alcohólicas', 'Vinos y Cervezas', 'ALIMENTOS', 'PARED'),
('Conservas', 'Alimentos en Conserva', 'ALIMENTOS', 'CABECERA'),
('Productos Mexicanos', 'Auténticos', 'ALIMENTOS', 'ESPECIALIZADA'),
('Delicatessen', 'Gourmet', 'ALIMENTOS', 'CENTRALES');

INSERT INTO empleados (nombre, apellido, edad, id_gondola) VALUES
('Juan', 'Pérez', 20, 1),
('Ana', 'Gómez', 22, 2),
('Luis', 'Martínez', 19, 3),
('María', 'López', 21, 4),
('Carlos', 'Ruiz', 23, 5),
('Sofía', 'Torres', 24, 6),
('José', 'Hernández', 25, 7),
('Lucía', 'Díaz', 18, 8),
('Ricardo', 'Sánchez', 26, 9),
('Elena', 'Castro', 30, 10),
('Fernando', 'Morales', 31, 11),
('Claudia', 'Jiménez', 28, 12),
('Andrés', 'Torres', 29, 13),
('Gabriela', 'Ruiz', 27, 14),
('Alberto', 'Rojas', 32, 15),
('Patricia', 'Romero', 33, 16),
('Javier', 'Silva', 34, 17),
('Laura', 'Ortega', 35, 18),
('Pedro', 'López', 36, 19),
('Martha', 'Medrano', 37, 20),
('Roberto', 'Castillo', 38, 21),
('Verónica', 'Salazar', 39, 22),
('Rosa', 'Fernández', 40, 23),
('Samuel', 'Arias', 41, 24),
('Silvia', 'Vega', 42, 25),
('Diego', 'Pineda', 43, 26),
('Ana', 'Serrano', 44, 27),
('Hugo', 'Martínez', 45, 28),
('Clara', 'López', 46, 29),
('Marco', 'Gómez', 47, 30),
('Lidia', 'Morales', 48, 31),
('Patricia', 'Ríos', 49, 32),
('Cristina', 'Salinas', 50, 6),  -- Here, I linked to the "Panadería"
('Jorge', 'Cordero', 51, 7),      -- Linked to "Carnes y Embutidos"
('Mónica', 'Díaz', 52, 19),       -- Linked to "Tecnología"
('Ricardo', 'Ramos', 53, 20),     -- Linked to "Product Gallery"
('Esteban', 'Alvarado', 54, 14),  -- Linked to "Cuidado de Mascotas"
('Gabriela', 'Calvo', 55, 16),    -- Linked to "Cosméticos y Cuidado Personal"
('Fernando', 'Medina', 56, 31),   -- Linked to "Casa y Jardín"
('Sergio', 'Torres', 57, 5),      -- Linked to "Bebidas"
('Natalia', 'González', 58, 12),  -- Linked to "Condimentos"
('Emilio', 'Pinto', 59, 30),      -- Linked to "Alimentos Congelados"
('Laura', 'Castro', 60, 15),      -- Linked to "Bolsos y Accesorios"
('Ricardo', 'Salas', 61, 39),     -- Linked to "Bebidas Alcohólicas"
('Isabel', 'Rojas', 62, 3),       -- Linked to "Frutas y Verduras"
('Julio', 'Cárdenas', 63, 4),     -- Linked to "Panadería"
('María', 'Serrano', 64, 18),     -- Linked to "Educación Infantil"
('Javier', 'López', 65, 12),      -- Linked to "Productos de Limpieza"
('Cristina', 'Pérez', 66, 11),    -- Linked to "Lácteos"
('José', 'Martínez', 67, 24);      -- Linked to "Bioquímica"

INSERT INTO productos (marca, producto, codigo_gondolas) VALUES
('Frutita', 'Manzana', 1),
('Verdura Fresh', 'Lechuga', 1),
('Carnes del Campo', 'Pollo', 2),
('Fiambres Selectos', 'Jamon', 2),
('Panadería Artística', 'Pan Fresco', 3),
('Dulces & Postres', 'Tarta de Frutas', 3),
('Lácteos Naturales', 'Leche Entera', 4),
('Quesos Gourmet', 'Queso Cheddar', 4),
('Bebidas Naturales', 'Jugo de Naranja', 5),
('Bebida Energética', 'Energía Plus', 5),
('Especias Caseras', 'Sal de Mar', 6),
('Salsas del Chef', 'Salsa de Tomate', 6),
('Snacks Crunchy', 'Papitas Fritas', 7),
('Chocolatería', 'Chocolate con Almendras', 7),
('Electrodomésticos XYZ', 'Tostadora', 8),
('Muebles Modernos', 'Silla de Cocina', 9),
('Pinturas Únicas', 'Pintura Acrílica', 10),
('Cuidado Personal XYZ', 'Jabón Artesanal', 11),
('Moda Actual', 'Zapatos Deportivos', 12),
('Juguetes Divertidos', 'Muñeca de Tela', 13),
('Cuidado Familiar', 'Detergente', 14),
('Libros de Cocina', 'Recetas de Chefs', 15),
('Tecnología Avanzada', 'Auriculares Bluetooth', 16),
('Cuidado de Mascotas', 'Comida para Perros', 17),
('Café Gourmet', 'Café Arábica', 18),
('Bebidas Alcohólicas', 'Vino Tinto', 19),
('Limpieza Ecológica', 'Limpiador Multisuperficie', 20),
('Cuidado del Hogar', 'Focos LED', 21),
('Alimentos Gourmet', 'Aceite de Oliva', 22),
('Bebidas Deshidratadas', 'Limonada', 23),
('Artículos de Fiesta', 'Globos', 24),
('Productos Orgánicos', 'Cereales Integrales', 25),
('Comida Rápida', 'Congelado de Papas Fritas', 26),
('Salsas Especiales', 'Salsa BBQ', 27),
('Cuidado Personal Orgánico', 'Crema Hidratante', 28),
('Menaje Científico', 'Termómetro de Cocina', 29),
('Decoración de Eventos', 'Luces LED', 30),
('Cuidado del Jardín', 'Fertilizante', 31),
('Suplementos Nutricionales', 'Proteína en Polvo', 32),
('Alimentos Saludables', 'Barritas de Granola', 33),
('Dulces Artesanales', 'Caramelos', 34),
('Jugos Naturales', 'Jugo de Manzana', 35),
('Productos de Invernadero', 'Tomate Orgánico', 36),
('Productos Sin Gluten', 'Galletas', 37),
('Alimentos Internacionales', 'Salsa de Soya', 38),
('Platos y Utensilios', 'Platos de Cartón', 39),
('Herramientas de Jardinería', 'Tijeras de Podar', 40),
('Electrónica', 'Baterías recargables', 41),
('Cuidado del Cabello', 'Champú Natural', 42),
('Comida Mexicana', 'Tortillas', 43),
('Cuidado de la Piel', 'Crema Solar', 44),
('Nutrición para Mascotas', 'Galletas para Perros', 45),
('Cuidado de la Salud', 'Vitaminas', 46),
('Productos para Niños', 'Comida para Bebés', 47),
('Artículos para Eventos', 'Mesa de Fiesta', 48),
('Vinos Premium', 'Vino Blanco', 49);